cache:
  key: ${CI_JOB_NAME}
  paths:
    - "out/"

variables:
  PREFIX: "riscv64-unknown-elf-"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

exec_test:
  stage: test
  image: jiegec/meowv64
  script:
    - cd testcases
    - make
    - cd ..
    - mill meowv64.test.test
