cache:
  key: ${CI_JOB_NAME}
  paths:
    - ".cache/"

variables:
  MILL_CLI: "-D coursier.cache=$CI_PROJECT_DIR/.cache"
  PREFIX: "riscv64-linux-gnu-"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  image: jiegec/meowv64
  script:
    - cd testcases
    - make custom riscv-tests
    - cd ..
  artifacts:
    paths:
      - testcases/

verilator_rocket_single_core_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - mill meowv64.runMain firtoolresolver.Main 1.62.1
    - cd verilator/SingleCoreConfig
    - PATH=$HOME/.cache/llvm-firtool/1.62.1/bin:$PATH make
    - ../common/test.sh
    - ../common/benchmark.sh

verilator_rocket_dual_core_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - mill meowv64.runMain firtoolresolver.Main 1.62.1
    - cd verilator/DualCoreConfig
    - PATH=$HOME/.cache/llvm-firtool/1.62.1/bin:$PATH make
    - ../common/test.sh
    - ../common/benchmark.sh
