cache:
  key: ${CI_JOB_NAME}
  paths:
    - ".cache/"

variables:
  MILL_CLI: "-D coursier.cache=$CI_PROJECT_DIR/.cache"
  PREFIX: "riscv64-unknown-elf-"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

exec_test:
  stage: test
  image: jiegec/meowv64
  script:
    - cd testcases
    - make
    - cd ..
    - mill $MILL_CLI meowv64.test.test
