cache:
  key: ${CI_JOB_NAME}
  paths:
    - ".cache/"

variables:
  MILL_CLI: "-D coursier.cache=$CI_PROJECT_DIR/.cache"
  PREFIX: "riscv64-unknown-elf-"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  image: jiegec/meowv64
  script:
    - cd testcases
    - make
    - cd ..
  artifacts:
    paths:
      - testcases/

scala_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - mill $MILL_CLI meowv64.test.test

verilator_single_core_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - cd verilator/SingleCoreDef
    - make
    - ../standalone/test.sh
    - ../standalone/benchmark.sh

verilator_double_core_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - cd verilator/DualCoreDef
    - make
    - ../standalone/test.sh
    - ../standalone/benchmark.sh

verilator_rocket_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - ./generate.sh
    - cd verilator/rocket
    - make
    - ./test.sh
    - ./benchmark.sh