cache:
  key: ${CI_JOB_NAME}
  paths:
    - "sbt-cache/.ivy/cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"

variables:
  SBT_VERSION: "0.13.9"
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy -Dsbt.repository.config=.gitlab-ci/repositories -Dsbt.override.build.repos=true"
  PREFIX: "riscv64-linux-gnu-"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

before_script:
  - yes | pacman -v -Syy || true
  - echo -e "y\n\n\n\n" | pacman -v -S riscv64-linux-gnu-gcc base-devel verilator || true

exec_test:
  stage: test
  image: chisel
  script:
    - cd testcases
    - make
    - cd ..
    - sbt test
