cache:
  key: ${CI_JOB_NAME}
  paths:
    - ".cache/"

variables:
  MILL_CLI: "-D coursier.cache=$CI_PROJECT_DIR/.cache"
  PREFIX: "riscv64-linux-gnu-"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  image: jiegec/meowv64
  script:
    - cd testcases
    - make
    - cd ..
  artifacts:
    paths:
      - testcases/

scala_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - mill $MILL_CLI meowv64.test.test

verilator_single_core_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - cd verilator/SingleCoreDef
    - make
    - ../common/test.sh
    - ../common/benchmark.sh

verilator_dual_core_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - cd verilator/DualCoreDef
    - make
    - ../common/test.sh
    - ../common/benchmark.sh

verilator_rocket_single_core_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - cd verilator/SingleCoreConfig
    - make
    - ../common/test.sh
    - ../common/benchmark.sh

verilator_rocket_dual_core_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - cd verilator/DualCoreConfig
    - make
    - ../common/test.sh
    - ../common/benchmark.sh
