cache:
  key: ${CI_JOB_NAME}
  paths:
    - ".cache/"

variables:
  MILL_CLI: "-D coursier.cache=$CI_PROJECT_DIR/.cache"
  PREFIX: "riscv64-unknown-elf-"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  image: jiegec/meowv64
  script:
    - cd testcases
    - make
    - cd ..

scala_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - mill $MILL_CLI meowv64.test.test

verilator_test:
  stage: test
  dependencies: 
    - build
  image: jiegec/meowv64
  script:
    - mill $MILL_CLI meowv64.runMain meowv64.Main
    - cd verilator
    - make
    - ./test.sh
    - ./benchmark.sh
    - cd ..
